'use client';

import React from 'react';

// Simulated AI hot stock tips (replace with real AI/ML backend)
const demoTips = [
  {
    symbol: 'NVDA',
    reason: 'AI momentum, strong earnings, and institutional buying',
    confidence: 0.97,
    action: 'Buy',
  },
  {
    symbol: 'TSLA',
    reason: 'Unusual options activity and positive sentiment',
    confidence: 0.93,
    action: 'Buy',
  },
  {
    symbol: 'AAPL',
    reason: 'Breakout pattern detected by deep learning model',
    confidence: 0.91,
    action: 'Buy',
  },
];

export default function HotStockTips() {
  // In production, fetch from AI backend
  return (
    <div className="glassmorphic neon-border rounded-xl p-6 shadow-xl flex flex-col gap-4 animate-fade-in">
      <h3 className="text-xl font-bold text-fuchsia-300 mb-2">🔥 AI Hot Stock Tips (Today)</h3>
      <ul className="space-y-3">
        {demoTips.map((tip, i) => (
          <li key={i} className="bg-black/40 rounded-lg p-3 flex flex-col gap-1">
            <span className="text-2xl font-extrabold text-cyan-400">{tip.symbol}</span>
            <span className="text-fuchsia-200">{tip.reason}</span>
            <span className="text-yellow-300 font-semibold">
              Confidence: {(tip.confidence * 100).toFixed(1)}%
            </span>
            <span className="text-green-400 font-bold">Action: {tip.action}</span>
          </li>
        ))}
      </ul>
      <div className="text-xs text-fuchsia-200 mt-2 italic">
        * These tips are generated by advanced AI models analyzing real-time data, news, and market
        signals.
      </div>
    </div>
  );
}
