[build]
  command = "pnpm build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[functions]
  directory = "netlify/functions"
